-- MySQL Script generated by MySQL Workbench
-- Dom 08 Abr 2018 21:44:41 -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OnFleek
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OnFleek
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OnFleek` DEFAULT CHARACTER SET utf8 ;
USE `OnFleek` ;

-- -----------------------------------------------------
-- Table `OnFleek`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnFleek`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(90) NOT NULL,
  `emailUsuario` VARCHAR(100) NOT NULL,
  `senhaUsuario` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnFleek`.`Titulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnFleek`.`Titulo` (
  `idTitulo` INT NOT NULL AUTO_INCREMENT,
  `nomeTitulo` VARCHAR(100) NOT NULL,
  `categoriaTitulo` CHAR(30) NOT NULL,
  `descricaoTitulo` VARCHAR(400) NOT NULL,
  PRIMARY KEY (`idTitulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnFleek`.`Usuario_Comenta_Titulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnFleek`.`Usuario_Comenta_Titulo` (
  `Usuario_idUsuario` INT NOT NULL,
  `Titulo_idTitulo` INT NOT NULL,
  `descricaoComentario` VARCHAR(500) NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Titulo_idTitulo`),
  CONSTRAINT `fk_Usuario_has_Titulo_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `OnFleek`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Titulo_Titulo1`
    FOREIGN KEY (`Titulo_idTitulo`)
    REFERENCES `OnFleek`.`Titulo` (`idTitulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnFleek`.`Usuario_Lista_Titulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnFleek`.`Usuario_Lista_Titulo` (
  `Usuario_idUsuario` INT NOT NULL,
  `Titulo_idTitulo` INT NOT NULL,
  `nomeLista` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Titulo_idTitulo`),
  CONSTRAINT `fk_Usuario_has_Titulo_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `OnFleek`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Titulo_Titulo2`
    FOREIGN KEY (`Titulo_idTitulo`)
    REFERENCES `OnFleek`.`Titulo` (`idTitulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
